name = "gchp-site"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "gchp"
database_id = "1cd37954-87a2-4df2-b9e5-97806e2ec43c"

[[r2_buckets]]
binding = "FILES"
bucket_name = "gchp-files"

[vars]
EMAIL_FROM = "Grant County Holiday Project <no-reply@grantcountyholidayproject.org>"
EMAIL_REPLY_TO = "skleinow@co.grant.wi.gov"
CONTACT_TO = "skleinow@co.grant.wi.gov"
